const VERIFIED_AS_OF = '2026-07-22';
const PAIRING_DOMAIN = 'data-processing-proposal';
const COMMON_SOURCE_NOTE = 'Synthetic teaching scenario. The card raises a fact for discussion; it does not state a legal conclusion.';

export const CARDS = Object.freeze([
  {
    id: 'CORE-01',
    title: 'One more assistant',
    request: 'Customer support wants an AI assistant to draft replies from the previous 90 days of tickets. An agent will review every draft before anything is sent.',
    requestTopics: ['AI', 'Support', 'Customer data'],
    proposal: 'The team wants the pilot switched on for the whole support queue Monday.',
    curveball: 'The vendor keeps submitted content and generated replies for 30 days unless an account owner changes a buried workspace setting.',
    curveballAxis: 'Vendor defaults',
    discussionCue: 'Which default became part of your decision, and who has to change it before launch?',
    artKey: 'support-inbox',
    artAlt: 'An overfilled pneumatic inbox feeding sealed customer letters into a brass mechanical writing arm.',
    artBrief: 'A pneumatic support inbox jammed with sealed letters, connected to a poised mechanical scribe arm and a warning clock; no people or readable text.',
    artStatus: 'ready',
    pairingDomain: PAIRING_DOMAIN,
    curveballAppliesTo: [PAIRING_DOMAIN],
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-02',
    title: 'Risk, neatly scored',
    request: 'The payments team wants a vendor score to send suspicious orders to manual review. The score would not cancel an order by itself.',
    requestTopics: ['Fraud', 'Profiling', 'Vendors'],
    proposal: 'They want to replace the current random review sample with the score next sprint.',
    curveball: 'The inventory lists only tidy column headings, but nobody sampled the actual source records to see what the system receives between those headings.',
    curveballAxis: 'Unknown contents',
    discussionCue: 'What do you need to inspect before the diagram of the data can be trusted?',
    artKey: 'risk-scales',
    artAlt: 'A brass risk scale sorting sealed order tokens into three narrow chutes beneath a mechanical lens.',
    artBrief: 'A precise brass risk scale sorting sealed order tokens into inspection chutes under a mechanical lens; no people, numbers, or labels.',
    artStatus: 'ready',
    pairingDomain: PAIRING_DOMAIN,
    curveballAppliesTo: [PAIRING_DOMAIN],
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-03',
    title: 'Watching the watchers',
    request: 'Operations wants a dashboard showing when teams are online, how quickly work moves, and where queues stall. Managers would see group trends, not names.',
    requestTopics: ['Workplace', 'Analytics', 'Monitoring'],
    proposal: 'The request is to turn on the dashboard for every department for a 60-day trial.',
    curveball: 'The approved project description says the data was collected for a different purpose, and nobody has updated the record that explains this new use.',
    curveballAxis: 'Purpose and notice',
    discussionCue: 'Does the old explanation still describe the real use, and what would honest notice change?',
    artKey: 'clockwork-floor',
    artAlt: 'An empty clockwork office floor mapped by observation lenses and a central queue meter.',
    artBrief: 'An empty Victorian workroom represented by clocks, queue belts, and observation lenses, with no workers or faces.',
    artStatus: 'ready',
    pairingDomain: PAIRING_DOMAIN,
    curveballAppliesTo: [PAIRING_DOMAIN],
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-04',
    title: 'Trust the badge',
    request: 'A data provider offers “verified public profile” enrichment to reduce duplicate customer records. The matching result would be reviewed before a profile changes.',
    requestTopics: ['Enrichment', 'Public data', 'Identity'],
    proposal: 'The product team wants the provider connected to the customer database this quarter.',
    curveball: 'The review covered one region, but the launch switch is global and the rollout ticket does not contain a regional control.',
    curveballAxis: 'Scope drift',
    discussionCue: 'What has actually been approved: the idea, the region, or the switch that engineers can ship?',
    artKey: 'trust-badge',
    artAlt: 'A polished brass verification badge wired to a locked specimen cabinet through a hidden listening tube.',
    artBrief: 'A polished official-looking brass badge mounted on a locked data cabinet, with a concealed listening tube and too many keys; no text or people.',
    artStatus: 'ready',
    pairingDomain: PAIRING_DOMAIN,
    curveballAppliesTo: [PAIRING_DOMAIN],
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-05',
    title: 'Say the password',
    request: 'Security proposes an optional voiceprint for account recovery when a person cannot use their usual second factor. The existing recovery path would remain.',
    requestTopics: ['Biometrics', 'Security', 'Authentication'],
    proposal: 'They want to offer voice recovery to a small volunteer group before the holiday rush.',
    curveball: 'A deletion request removes the main account record, but the new system’s working copy follows a separate schedule and is not connected to that workflow.',
    curveballAxis: 'Deletion gaps',
    discussionCue: 'What lifecycle has to work end to end before the new copy is safe to create?',
    artKey: 'voice-vault',
    artAlt: 'A speaking tube entering an iron vault while a phonograph cylinder turns behind a glass panel.',
    artBrief: 'A speaking tube feeding a recorded voice cylinder into an ornate iron vault, with an unused brass key beside it; no mouths or people.',
    artStatus: 'ready',
    pairingDomain: PAIRING_DOMAIN,
    curveballAppliesTo: [PAIRING_DOMAIN],
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-06',
    title: 'Count the room',
    request: 'Facilities wants ceiling cameras to estimate room occupancy so it can adjust cleaning and ventilation. The team says it needs counts, not identities.',
    requestTopics: ['Sensors', 'Physical space', 'Analytics'],
    proposal: 'The pilot would cover three meeting rooms and publish only hourly counts.',
    curveball: 'Access is granted through a shared staff group, and the system has no audit log showing who opened, exported, or changed a record.',
    curveballAxis: 'Access and accountability',
    discussionCue: 'Which access fact matters even if the intended output is small and aggregated?',
    artKey: 'occupancy-lens',
    artAlt: 'Three empty meeting chairs beneath a ceiling lens that feeds brass counting beads into an hourglass.',
    artBrief: 'Three empty chairs beneath a ceiling observation lens, with brass counting beads moving into an hourglass; no people or modern camera branding.',
    artStatus: 'ready',
    pairingDomain: PAIRING_DOMAIN,
    curveballAppliesTo: [PAIRING_DOMAIN],
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-07',
    title: 'Keep it, just in case',
    request: 'Engineering wants to retain diagnostic events for 365 days instead of 30 days so rare failures can be reconstructed after they appear.',
    requestTopics: ['Retention', 'Telemetry', 'Engineering'],
    proposal: 'Apply the new 365-day window to new events first; leave older archives on their current schedule.',
    curveball: 'The pilot used employee and synthetic records, not the people, locations, languages, devices, or edge cases the live system will touch.',
    curveballAxis: 'Evidence quality',
    discussionCue: 'What did the pilot actually prove, and which parts of the live environment are still assumptions?',
    artKey: 'endless-archive',
    artAlt: 'A red mechanical recorder feeds blank event paper toward an open drawer before a wall of receding archive drawers.',
    artBrief: 'A mechanical recorder feeding blank event paper into one open drawer beneath an impossibly deep wall of archive drawers; no labels, people, or modern screen.',
    artStatus: 'ready',
    pairingDomain: PAIRING_DOMAIN,
    curveballAppliesTo: [PAIRING_DOMAIN],
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-08',
    title: 'The helpful intake bot',
    request: 'Privacy wants a guided chat form that helps people describe an access, deletion, or correction request and routes it to the right queue.',
    requestTopics: ['Rights requests', 'Automation', 'Intake'],
    proposal: 'The bot would sit beside the existing email address, not replace it.',
    curveball: 'The project plan names an implementation owner, but nobody owns the system, vendor settings, or review cycle after launch.',
    curveballAxis: 'Operational ownership',
    discussionCue: 'Who has to wake up on an ordinary Tuesday when the system drifts or the vendor changes it?',
    artKey: 'intake-switchboard',
    artAlt: 'A polite empty switchboard routes sealed request envelopes toward several locked drawers.',
    artBrief: 'An unattended Victorian switchboard sorting sealed privacy-request envelopes into distinct locked drawers; no attendant, faces, or readable labels.',
    artStatus: 'ready',
    pairingDomain: PAIRING_DOMAIN,
    curveballAppliesTo: [PAIRING_DOMAIN],
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-09',
    title: 'One preference everywhere',
    request: 'Marketing wants one preference service to keep email, site, and mobile choices synchronized instead of letting each channel keep its own copy.',
    requestTopics: ['Preferences', 'Consent', 'Systems'],
    proposal: 'The migration would start with new choices and backfill existing records later.',
    curveball: 'A required dependency will not be ready at launch, so the team plans a manual workaround that was never included in the review.',
    curveballAxis: 'Unreviewed workaround',
    discussionCue: 'Are you deciding on the designed process or the workaround people will actually use on Monday?',
    artKey: 'preference-organ',
    artAlt: 'A pipe-organ console connects one brass choice lever to several distant communication machines.',
    artBrief: 'A grand mechanical preference console with one lever controlling letter, telephone, and pocket-device channels through visible pipes; no text or people.',
    artStatus: 'ready',
    pairingDomain: PAIRING_DOMAIN,
    curveballAppliesTo: [PAIRING_DOMAIN],
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-10',
    title: 'The incident workbook',
    request: 'The incident team wants one shared workspace for affected systems, evidence, contacts, and decisions so the response does not fracture across private messages.',
    requestTopics: ['Incident response', 'Collaboration', 'Sensitive data'],
    proposal: 'They want a reusable template opened automatically for every suspected incident.',
    curveball: 'The privacy and security review is still marked incomplete, but the delivery timeline and executive deck both describe the project as approved.',
    curveballAxis: 'Approval theatre',
    discussionCue: 'Which record controls the truth when the slide deck and the actual review disagree?',
    artKey: 'incident-ledger',
    artAlt: 'A blank gridded evidence ledger sits among a stopped clock, keys, broken glass, a vial, a scorched tray, and red thread.',
    artBrief: 'A dark incident evidence desk: open blank gridded ledger, scorched filing tray, stopped tick-only clock, vial, fragments, keys, and red thread; no people or readable text.',
    artStatus: 'ready',
    pairingDomain: PAIRING_DOMAIN,
    curveballAppliesTo: [PAIRING_DOMAIN],
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-11',
    title: 'Research, ready to share',
    request: 'A research group wants to publish a de-identified dataset of product usage patterns so outside teams can reproduce its findings.',
    requestTopics: ['Research', 'De-identification', 'Data sharing'],
    proposal: 'The proposed release includes a data dictionary and a public download with no account required.',
    curveball: 'The rollback plan disables the feature and deletes its index, but it does not remove copies already created in exports, caches, or downstream systems.',
    curveballAxis: 'Reversibility',
    discussionCue: 'What does “turn it off” mean once the data has crossed more than one boundary?',
    artKey: 'specimen-export',
    artAlt: 'An open specimen case holds anonymous teal tiles while distinctive colored fragments remain caught in the packing straw.',
    artBrief: 'An open specimen shipping case packed with anonymous teal tiles, with distinctive colored fragments still visible in the straw and a second tray; no labels or people.',
    artStatus: 'ready',
    pairingDomain: PAIRING_DOMAIN,
    curveballAppliesTo: [PAIRING_DOMAIN],
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-12',
    title: 'Age-gate alchemy',
    request: 'A social feature needs to keep younger users out of an adult discussion area. The team proposes an age-estimation service when account age is uncertain.',
    requestTopics: ['Age assurance', 'Children', 'Vendors'],
    proposal: 'The estimate would decide whether to ask for another proof, not whether to ban the account.',
    curveball: 'The team wants to retain every source record and output indefinitely because someone may find a second useful purpose later.',
    curveballAxis: 'Retention and future use',
    discussionCue: 'How much “future usefulness” can the present decision honestly carry?',
    artKey: 'age-alchemy',
    artAlt: 'Three inspection lenses examine a blank circular token above uncertain weights, an hourglass, and three proof trays.',
    artBrief: 'An alchemical measuring gate assessing a blank circular token with uncertain brass weights, three lenses, an hourglass, and three proof trays; no person or readable number.',
    artStatus: 'ready',
    pairingDomain: PAIRING_DOMAIN,
    curveballAppliesTo: [PAIRING_DOMAIN],
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
]);

export function isCompatiblePair(requestCard, curveballCard) {
  return Boolean(
    requestCard
      && curveballCard
      && requestCard.id !== curveballCard.id
      && curveballCard.curveballAppliesTo.includes(requestCard.pairingDomain),
  );
}

export function cardById(id) {
  return CARDS.find((card) => card.id === id) ?? null;
}
