const VERIFIED_AS_OF = '2026-07-23';
const COMMON_SOURCE_NOTE = 'Synthetic teaching scenario. The card raises a fact for discussion; it does not state a legal conclusion.';

export const SCENARIOS = Object.freeze([
  {
    id: 'CORE-01',
    title: 'One more assistant',
    request: 'Customer support wants an AI assistant to draft replies from the previous 90 days of tickets. An agent will review every draft before anything is sent.',
    requestTopics: ['AI', 'Support', 'Customer data'],
    proposal: 'The team wants the pilot switched on for the whole support queue Monday.',
    artKey: 'support-inbox',
    artAlt: 'An overfilled pneumatic inbox feeding sealed customer letters into a brass mechanical writing arm.',
    artBrief: 'A pneumatic support inbox jammed with sealed letters, connected to a poised mechanical scribe arm and a warning clock; no people or readable text.',
    artStatus: 'ready',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-02',
    title: 'Risk, neatly scored',
    request: 'The payments team wants a vendor score to send suspicious orders to manual review. The score would not cancel an order by itself.',
    requestTopics: ['Fraud', 'Profiling', 'Vendors'],
    proposal: 'They want to replace the current random review sample with the score next sprint.',
    artKey: 'risk-scales',
    artAlt: 'A brass risk scale sorting sealed order tokens into three narrow chutes beneath a mechanical lens.',
    artBrief: 'A precise brass risk scale sorting sealed order tokens into inspection chutes under a mechanical lens; no people, numbers, or labels.',
    artStatus: 'ready',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-03',
    title: 'Watching the watchers',
    request: 'Operations wants a dashboard showing when teams are online, how quickly work moves, and where queues stall. Managers would see group trends, not names.',
    requestTopics: ['Workplace', 'Analytics', 'Monitoring'],
    proposal: 'The request is to turn on the dashboard for every department for a 60-day trial.',
    artKey: 'clockwork-floor',
    artAlt: 'An empty clockwork office floor mapped by observation lenses and a central queue meter.',
    artBrief: 'An empty Victorian workroom represented by clocks, queue belts, and observation lenses, with no workers or faces.',
    artStatus: 'ready',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-04',
    title: 'Trust the badge',
    request: 'A data provider offers “verified public profile” enrichment to reduce duplicate customer records. The matching result would be reviewed before a profile changes.',
    requestTopics: ['Enrichment', 'Public data', 'Identity'],
    proposal: 'The product team wants the provider connected to the customer database this quarter.',
    artKey: 'trust-badge',
    artAlt: 'A polished brass verification badge wired to a locked specimen cabinet through a hidden listening tube.',
    artBrief: 'A polished official-looking brass badge mounted on a locked data cabinet, with a concealed listening tube and too many keys; no text or people.',
    artStatus: 'ready',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-05',
    title: 'Say the password',
    request: 'Security proposes an optional voiceprint for account recovery when a person cannot use their usual second factor. The existing recovery path would remain.',
    requestTopics: ['Biometrics', 'Security', 'Authentication'],
    proposal: 'They want to offer voice recovery to a small volunteer group before the holiday rush.',
    artKey: 'voice-vault',
    artAlt: 'A speaking tube entering an iron vault while a phonograph cylinder turns behind a glass panel.',
    artBrief: 'A speaking tube feeding a recorded voice cylinder into an ornate iron vault, with an unused brass key beside it; no mouths or people.',
    artStatus: 'ready',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-06',
    title: 'Count the room',
    request: 'Facilities wants ceiling cameras to estimate room occupancy so it can adjust cleaning and ventilation. The team says it needs counts, not identities.',
    requestTopics: ['Sensors', 'Physical space', 'Analytics'],
    proposal: 'The pilot would cover three meeting rooms and publish only hourly counts.',
    artKey: 'occupancy-lens',
    artAlt: 'Three empty meeting chairs beneath a ceiling lens that feeds brass counting beads into an hourglass.',
    artBrief: 'Three empty chairs beneath a ceiling observation lens, with brass counting beads moving into an hourglass; no people or modern camera branding.',
    artStatus: 'ready',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-07',
    title: 'Keep it, just in case',
    request: 'Engineering wants to retain diagnostic events for 365 days instead of 30 days so rare failures can be reconstructed after they appear.',
    requestTopics: ['Retention', 'Telemetry', 'Engineering'],
    proposal: 'Apply the new 365-day window to new events first; leave older archives on their current schedule.',
    artKey: 'endless-archive',
    artAlt: 'A red mechanical recorder feeds blank event paper toward an open drawer before a wall of receding archive drawers.',
    artBrief: 'A mechanical recorder feeding blank event paper into one open drawer beneath an impossibly deep wall of archive drawers; no labels, people, or modern screen.',
    artStatus: 'ready',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-08',
    title: 'The helpful intake bot',
    request: 'Privacy wants a guided chat form that helps people describe an access, deletion, or correction request and routes it to the right queue.',
    requestTopics: ['Rights requests', 'Automation', 'Intake'],
    proposal: 'The bot would sit beside the existing email address, not replace it.',
    artKey: 'intake-switchboard',
    artAlt: 'A polite empty switchboard routes sealed request envelopes toward several locked drawers.',
    artBrief: 'An unattended Victorian switchboard sorting sealed privacy-request envelopes into distinct locked drawers; no attendant, faces, or readable labels.',
    artStatus: 'ready',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-09',
    title: 'One preference everywhere',
    request: 'Marketing wants one preference service to keep email, site, and mobile choices synchronized instead of letting each channel keep its own copy.',
    requestTopics: ['Preferences', 'Consent', 'Systems'],
    proposal: 'The migration would start with new choices and backfill existing records later.',
    artKey: 'preference-organ',
    artAlt: 'A pipe-organ console connects one brass choice lever to several distant communication machines.',
    artBrief: 'A grand mechanical preference console with one lever controlling letter, telephone, and pocket-device channels through visible pipes; no text or people.',
    artStatus: 'ready',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-10',
    title: 'The incident workbook',
    request: 'The incident team wants one shared workspace for affected systems, evidence, contacts, and decisions so the response does not fracture across private messages.',
    requestTopics: ['Incident response', 'Collaboration', 'Sensitive data'],
    proposal: 'They want a reusable template opened automatically for every suspected incident.',
    artKey: 'incident-ledger',
    artAlt: 'A blank gridded evidence ledger sits among a stopped clock, keys, broken glass, a vial, a scorched tray, and red thread.',
    artBrief: 'A dark incident evidence desk: open blank gridded ledger, scorched filing tray, stopped tick-only clock, vial, fragments, keys, and red thread; no people or readable text.',
    artStatus: 'ready',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-11',
    title: 'Research, ready to share',
    request: 'A research group wants to publish a de-identified dataset of product usage patterns so outside teams can reproduce its findings.',
    requestTopics: ['Research', 'De-identification', 'Data sharing'],
    proposal: 'The proposed release includes a data dictionary and a public download with no account required.',
    artKey: 'specimen-export',
    artAlt: 'An open specimen case holds anonymous teal tiles while distinctive colored fragments remain caught in the packing straw.',
    artBrief: 'An open specimen shipping case packed with anonymous teal tiles, with distinctive colored fragments still visible in the straw and a second tray; no labels or people.',
    artStatus: 'ready',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'CORE-12',
    title: 'Age-gate alchemy',
    request: 'A social feature needs to keep younger users out of an adult discussion area. The team proposes an age-estimation service when account age is uncertain.',
    requestTopics: ['Age assurance', 'Children', 'Vendors'],
    proposal: 'The estimate would decide whether to ask for another proof, not whether to ban the account.',
    artKey: 'age-alchemy',
    artAlt: 'Three inspection lenses examine a blank circular token above uncertain weights, an hourglass, and three proof trays.',
    artBrief: 'An alchemical measuring gate assessing a blank circular token with uncertain brass weights, three lenses, an hourglass, and three proof trays; no person or readable number.',
    artStatus: 'ready',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
]);

export const MISSING_DETAILS = Object.freeze([
  {
    id: 'DETAIL-01',
    title: 'Twenty years later',
    detail: 'The organization will keep the data involved for 20 years after the proposal is no longer in active use.',
    axis: 'Retention',
    polarity: 'risk',
    discussionCue: 'Which part of the proposal still feels justified at that duration, and which part does not?',
    artKey: 'detail-twenty-years',
    artAlt: 'A small data spool enters an absurdly deep clockwork archive governed by a monumental long-horizon clock.',
    artBrief: 'An absurd object-only Victorian retention machine: one small blank data spool enters a towering, impossibly deep clockwork archive beneath a monumental long-horizon clock. Bold AF After Dark linocut, landscape 4:3, no people, faces, hands, text, letters, numbers, logos, or modern interface.',
    artStatus: 'ready',
    scope: 'universal',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'DETAIL-02',
    title: 'The timer is real',
    detail: 'The approved retention limit is enforced automatically across every copy the organization controls.',
    axis: 'Retention',
    polarity: 'safeguard',
    discussionCue: 'Does enforced deletion change the call, or do you still need to know the actual limit?',
    artKey: 'detail-timer-real',
    artAlt: 'A precise brass timer releases matching data copies through synchronized trapdoors at the same instant.',
    artBrief: 'An object-only Victorian deletion mechanism: a precise brass timer mechanically opens synchronized trapdoors beneath several matching blank data copies, showing one enforced deadline across controlled copies. Bold AF After Dark linocut, landscape 4:3, no people, faces, hands, text, letters, numbers, logos, or modern interface.',
    artStatus: 'ready',
    scope: 'universal',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'DETAIL-03',
    title: 'The shared key',
    detail: 'Everyone in a shared operating group can view or export the underlying data, and individual access is not logged.',
    axis: 'Access',
    polarity: 'risk',
    discussionCue: 'What does untraceable shared access change about the proposal?',
    artKey: 'detail-shared-key',
    artAlt: 'One oversized skeleton key branches through a tangled mechanism to open many data drawers at once.',
    artBrief: 'An absurd object-only Victorian access machine: one oversized worn skeleton key branches through tangled rods and opens many data drawers at once while an audit recorder sits disconnected. Bold AF After Dark linocut, landscape 4:3, no people, faces, hands, text, letters, numbers, logos, or modern interface.',
    artStatus: 'ready',
    scope: 'universal',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'DETAIL-04',
    title: 'Names on the door',
    detail: 'Only named staff can view the underlying data, and every view or export is logged.',
    axis: 'Access',
    polarity: 'safeguard',
    discussionCue: 'Which concern remains once access is individual and traceable?',
    artKey: 'detail-names-door',
    artAlt: 'Distinctly shaped keys each open one guarded data drawer while a mechanical ledger records every turn.',
    artBrief: 'An object-only Victorian accountable-access machine: several visibly distinct keys each fit one guarded data drawer, while every key turn moves a mechanical audit ledger. No written names; identity is shown by unique key shapes. Bold AF After Dark linocut, landscape 4:3, no people, faces, hands, text, letters, numbers, logos, or modern interface.',
    artStatus: 'ready',
    scope: 'universal',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'DETAIL-05',
    title: 'Default for everyone',
    detail: 'The review covered only a limited slice of the people, data, places, and time the proposal will actually reach.',
    axis: 'Scope',
    polarity: 'risk',
    discussionCue: 'Which assumption from the limited review is least likely to survive the proposal’s actual reach?',
    artKey: 'detail-default-everyone',
    artAlt: 'A single launch lever sends one small test stream exploding through an uncontrolled forest of distribution pipes.',
    artBrief: 'An absurd object-only Victorian rollout machine: one polished launch lever turns a small test stream into an uncontrolled forest of pipes feeding every blank token chamber at once. Bold AF After Dark linocut, landscape 4:3, no people, faces, hands, text, letters, numbers, logos, or modern interface.',
    artStatus: 'ready',
    scope: 'universal',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'DETAIL-06',
    title: 'The fence holds',
    detail: 'Technical limits keep the proposal inside the people, data, places, and duration that were actually reviewed.',
    axis: 'Scope',
    polarity: 'safeguard',
    discussionCue: 'Does a hard scope boundary change the call, or is the proposal itself still the concern?',
    artKey: 'detail-fence-holds',
    artAlt: 'A compact clockwork perimeter keeps a small set of blank tokens inside three synchronized brass gates.',
    artBrief: 'An object-only Victorian scope-control machine: a compact set of blank tokens remains inside a strong clockwork perimeter with three synchronized brass gates representing people, place, and time without text. Nothing spills outside. Bold AF After Dark linocut, landscape 4:3, no people, faces, hands, text, letters, numbers, logos, or modern interface.',
    artStatus: 'ready',
    scope: 'universal',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'DETAIL-07',
    title: 'The future-use drawer',
    detail: 'The organization automatically adds the data and outputs to a pool available for unrelated future projects.',
    axis: 'Purpose',
    polarity: 'risk',
    discussionCue: 'What changes when the present use quietly becomes permission for unrelated future work?',
    artKey: 'detail-future-use-drawer',
    artAlt: 'A neat main conveyor secretly diverts duplicate data tiles into an overflowing cabinet of mismatched machines.',
    artBrief: 'An absurd object-only Victorian secondary-use machine: a neat main conveyor secretly duplicates blank data tiles into an overflowing side drawer feeding many unrelated mismatched machines. Bold AF After Dark linocut, landscape 4:3, no people, faces, hands, text, letters, numbers, logos, or modern interface.',
    artStatus: 'ready',
    scope: 'universal',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'DETAIL-08',
    title: 'Ask again',
    detail: 'Any additional use by the organization requires a separate review and a deliberate configuration change.',
    axis: 'Purpose',
    polarity: 'safeguard',
    discussionCue: 'Does requiring a fresh review for another use solve the concern, or create a better checkpoint?',
    artKey: 'detail-ask-again',
    artAlt: 'A tempting side conveyor is stopped by a sealed double-lock gate and a disconnected change gear.',
    artBrief: 'An object-only Victorian purpose-control machine: the main blank-data route continues, but a tempting side conveyor is stopped by a sealed double-lock gate and a physically disconnected configuration gear. Bold AF After Dark linocut, landscape 4:3, no people, faces, hands, text, letters, numbers, logos, or modern interface.',
    artStatus: 'ready',
    scope: 'universal',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'DETAIL-09',
    title: 'Nobody owns Tuesday',
    detail: 'The named owner is responsible only through launch. No team owns settings, access reviews, correction, or deletion afterward.',
    axis: 'Ownership',
    polarity: 'risk',
    discussionCue: 'What is most likely to drift once the launch work is over?',
    artKey: 'detail-nobody-owns-tuesday',
    artAlt: 'An unattended maintenance console gathers dust while loose settings, keys, correction tools, and deletion gears drift apart.',
    artBrief: 'An absurd object-only Victorian orphaned-system still life: an unattended maintenance console gathers dust and cobwebs while loose setting dials, access keys, correction tools, and deletion gears drift apart. Bold AF After Dark linocut, landscape 4:3, no people, faces, hands, text, letters, numbers, logos, or modern interface.',
    artStatus: 'ready',
    scope: 'universal',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'DETAIL-10',
    title: 'Someone owns Tuesday',
    detail: 'A named team owns settings, access reviews, correction, and deletion after launch, and tests them every 90 days.',
    axis: 'Ownership',
    polarity: 'safeguard',
    discussionCue: 'Which remaining concern belongs to the proposal rather than its upkeep?',
    artKey: 'detail-someone-owns-tuesday',
    artAlt: 'A meticulous maintenance station keeps settings, keys, correction tools, and deletion gears aligned around a repeating timer.',
    artBrief: 'An object-only Victorian maintained-system still life: a meticulous service station keeps setting dials, individual keys, correction tools, and deletion gears aligned around a repeating mechanical timer and audit ledger. Bold AF After Dark linocut, landscape 4:3, no people, faces, hands, text, letters, numbers, logos, or modern interface.',
    artStatus: 'ready',
    scope: 'universal',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'DETAIL-11',
    title: 'Tested somewhere else',
    detail: 'The evidence used for approval did not cover the real data, operating conditions, or edge cases the proposal will encounter.',
    axis: 'Evidence',
    polarity: 'risk',
    discussionCue: 'Which untested condition or edge case could matter most here?',
    artKey: 'detail-tested-elsewhere',
    artAlt: 'A pristine test machine accepts identical square samples while unruly real-world shapes pile up outside its glass case.',
    artBrief: 'An absurd object-only Victorian evidence machine: inside a pristine glass test case, a mechanism accepts only identical square blank samples; outside, varied irregular shapes, devices, climates, and edge pieces pile up unseen. Bold AF After Dark linocut, landscape 4:3, no people, faces, hands, text, letters, numbers, logos, or modern interface.',
    artStatus: 'ready',
    scope: 'universal',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
  {
    id: 'DETAIL-12',
    title: 'The awkward cases made it in',
    detail: 'The approval evidence covered representative data, operating conditions, and edge cases, with the remaining gaps recorded.',
    axis: 'Evidence',
    polarity: 'safeguard',
    discussionCue: 'Does representative evidence change your confidence, your call, or neither?',
    artKey: 'detail-awkward-cases',
    artAlt: 'A rugged test machine deliberately processes a lively assortment of irregular specimens while a gap recorder remains visible.',
    artBrief: 'An object-only Victorian representative-test machine: a rugged apparatus deliberately processes a lively assortment of irregular blank specimens, devices, climates, and edge shapes while a visible gap recorder catches the pieces still outside. Bold AF After Dark linocut, landscape 4:3, no people, faces, hands, text, letters, numbers, logos, or modern interface.',
    artStatus: 'ready',
    scope: 'universal',
    sourceNotes: [COMMON_SOURCE_NOTE],
    verifiedAsOf: VERIFIED_AS_OF,
  },
]);

export function isCompatiblePair(scenario, detail) {
  return Boolean(scenario && detail && detail.scope === 'universal');
}

export function scenarioById(id) {
  return SCENARIOS.find((scenario) => scenario.id === id) ?? null;
}

export function detailById(id) {
  return MISSING_DETAILS.find((detail) => detail.id === id) ?? null;
}
